name: "Deploy Go Application"
description: "Deploy App to AWS EC2"

inputs:
  registry:
    description: "Container Registry"
    required: true
  image-name:
    description: "Image Name"
    required: true
  image-tag:
    description: "Image Tag"
    required: true

runs:
  using: "composite"
  steps:
    - name: Pull docker image
      id: pull-step
      run: docker pull  ${{ inputs.registry }}/${{ inputs.image-name}}:${{ inputs.image-tag }}
      shell: bash
    - name: Delete old container
      id: delete-step
      run: docker rm -f go-app-container
      shell: bash
    - name: Run docker container
      id: run-step
      run: docker run -d -p 8080:8080 --name go-app-container ${{ inputs.registry }}/${{ inputs.image-name}}:${{ inputs.image-tag }}

      shell: bash
