name: "Deploy Go Application"
description: "Deploy App to AWS EC2"

inputs:
  registry:
    description: "Container Registry"
    required: true
  image-name:
    description: "Image Name"
    required: true
  image-tag:
    description: "Image Tag"
    required: true

runs:
  uses: "composite"
  steps:
    - name: Pull docker image
      run: docker pull  ${{ inputs.registry }}/${{ inputs.image-name}}:${{ inputs.image-tag }}
    - name: Delete old container
      run: docker rm -f go-app-container
    - name: Run docker container
      run: docker run -d -p 4040:4040 --name go-app-container ${{ inputs.registry }}/${{ inputs.image-name}}:${{ inputs.image-tag }}

#jobs:
#  deploy:
#    runs-on: self-hosted
#    steps:
#      - name: Pull docker image
#        run: docker pull gchr.io/maliciousbucket/repos:latest
#      - name: Delete old container
#        run: docker rm -f go-app-container
#      - name: Run docker container
#        run: docker run -d -p 4040:4040 --name go-app-container gchr.io/maliciousbucket/repos:latest