
name: "Build-Publish"
description: "Build and Publish Image"

inputs:
  registry:
    description: Container Registry
    required: true
  username:
    description: GitHub User
    required: true
  image-name:
    description: Image Name
    required: true
  token:
    description: Token / Password for GitHub
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      id: checkout-step
    - name: Log in to the Container registry
      id: login-step
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.image-name}}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags:
          - ${{ steps.meta.outputs.tags }}
          - latest
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation
      id: artifact-step
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ${{ inputs.registry }}/${{ inputs.image-name }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true

