name: Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build Go App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
      - name: Build Application
        run: |
          go build .