name: Deploy Go Application

on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull gchr.io/maliciousbucket/repos:latest
      - name: Delete old container
        run: docker rm -f go-app-container
      - name: Run docker container
        run: docker run -d -p 4040:4040 --name go-app-container gchr.io/maliciousbucket/repos:latest