name: Build, Test, Publish and Deploy

on:
  push:
    branches: ["release"]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Test Application
        uses: ./.github/actions/test.yaml

      - name: Publish image to registry
        uses: ./.github/actions/publish-image.yaml

      - name: Deploy Application
        uses: ./.github/actions/deploy.yaml


