name: Build, Test, Publish and Deploy

on:
  push:
    branches: ["release"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish image to registry
        uses: ./.github/actions/publish
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          image-name: ${{ env.IMAGE_NAME }}
          token: ${{ secrets.TOKEN }}
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy Application
        uses: ./.github/actions/deploy
        with:
          image-name: ${{ env.IMAGE_NAME }}
          image-tag: "latest"
          registry: ${{ env.REGISTRY }}


