name: Build, Test, Publish and Deploy

on:
  push:
    branches: ["release"]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Publish image to registry
        uses: ./.github/actions/publish/action.yaml

      - name: Deploy Application
        uses: ./.github/actions/deploy/action.yaml


