name: Go Lint & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  lint:
    name: Lint Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: 1.61.0

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.2"
      - uses: actions/checkout@v4
      - name: Test
        run: go test -v ./...