name: Go Lint & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  GO_VERSION: 1.23.2


jobs:
  lint:
    name: Lint Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Lint Go
        uses: ./.github/actions/lint
        with:
          go-version: ${{ env.GO_VERSION }}

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v4
      - name: Test
        uses: ./.github/actions/test
        with:
          go-version: ${{ env.GO_VERSION }}